name: AegisFlow CI

on:
  push:
    branches: [main]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up directories
      run: mkdir -p reports sbom

    - name: Install tools
      run: |
        pip install semgrep
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
        curl -sSfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

    - name: Semgrep scan
      run: semgrep --config ./semgrep-rules/ --json > reports/semgrep.json

    - name: Generate SBOM
      run: syft dir:app/ --source-name=aegisflow --source-version=0.1.0 -o json > sbom/sbom.json

    - name: Trivy scan
      run: trivy fs app/ > reports/trivy.txt

    - name: OTX threat check
      run: bash scripts/otx_sbom_check.sh sbom/sbom.json

    - name: Dark web threat simulation
      run: bash scripts/dark_web_check.sh

    - name: Summarize scan results
      run: python analysis/summarize.py

    - name: Upload all scan reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
       name: scan-reports
       path: reports/

